[package]
name = "skilld-native"

version.workspace = true

edition.workspace = true

license.workspace = true

repository.workspace = true

rust-version.workspace = true

[[bin]]
name = "skilld"
path = "src/main.rs"

[dependencies]
skilld-auth.workspace = true

skilld-command.workspace = true

skilld-core.workspace = true

skilld-ui.workspace = true

tempfile.workspace = true

terminal_size.workspace = true

ureq = { version = "=3.1.4", default-features = false, features = [ "rustls" ] }

url.workspace = true

[target.'cfg(not(target_os = "wasi"))'.dependencies]
crossterm = { version = "=0.28.1", default-features = false, features = [
  "events",
  "windows",
] }
ratatui = { version = "=0.29.0", default-features = false, features = [ "crossterm" ] }

unicode-width.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.29.0", features = [ "term" ] }

[dev-dependencies]
skilld-ui.workspace = true
