[package]
name = "skilld-native"

version.workspace = true

edition.workspace = true

license.workspace = true

repository.workspace = true

rust-version.workspace = true

[[bin]]
name = "skilld"
path = "src/main.rs"

[dependencies]
skilld-auth.workspace = true

skilld-command.workspace = true

skilld-core.workspace = true

tempfile.workspace = true

ureq = { version = "=3.1.4", default-features = false, features = [ "rustls" ] }

url.workspace = true
